coverage_service: coveralls
ci_service: circleci
xcodeproj: PubnativeLite/HyBid.xcodeproj
scheme: HyBid
workspace: HyBid.xcworkspace
ignore:
    - "dependencies/**"
    - "circleci/*"
    - "PubnativeLite/HyBidDemo/*"
    - "PubnativeLite/HyBidTests/*"
    - "../*"
